# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc1c60f3666e9f8b74f32b5323355715fb48802f0462609ea7c831fbd344ba6b3fee11f0f200dbdd35f3db74d908e3c20e225d9f8c45b1135a9850258ec88a8
  cloud_name: db5orfik4
  api_key: '344698462367118'
  api_secret: zRfkQzo8hmpMtSxjt-eSqrKv4Ss
test:
  secret_key_base: f8d52722c7ec85445390872148c468da81d71e2d80007098657f895be1a0cc4e172ca5cc487f1032efd09c0448f72ef2eb403f4b900c1ec43fea9cc3f5abee3c
  cloud_name: db5orfik4
  api_key: '344698462367118'
  api_secret: zRfkQzo8hmpMtSxjt-eSqrKv4Ss
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloud_name: db5orfik4
  api_key: '344698462367118'
  api_secret: zRfkQzo8hmpMtSxjt-eSqrKv4Ss
